# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: sudo apt-get install python3.6

- script: sudo pip install wheel
  displayName: 'wheel install'
  
  
- script: pip3 install ansible[azure]
  displayName: 'Install Ansible and the Azure modules'

- script: pip install ansible==2.7
    
- script: ansible-playbook create_env.yml
