# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: pip install ansible[azure]
  displayName: 'Install Ansible and the Azure modules'
  
- name: Print message if ansible version is greater than 2.7.0
  debug:
    msg: "Ansible version is  {{ ansible_version.full }}"
  
  
- script: ansible-playbook create_env.yml
