# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: sudo apt-get autoremove python2.7
  
- script: sudo apt-get install python3.6

- script: pip3 install wheel 

- script: pip3 install --upgrade pip

- script: pip3 install packaging

- script: sudo apt-get install python3-setuptools

#- script: pip3 install ansible==2.9.2

- script: pip3 install ansible[azure]
  displayName: 'Install Ansible and the Azure modules'
  
- script: python -m pip uninstall ansible && python3 -m pip install ansible
  
#- script: sudo apt-get install python3.6

#- script: sudo apt-get install -y python-setuptools

#- script: pip3 install wheel 

#- script: pip3 install --upgrade pip

#- script: pip3 install packaging

#- script: sudo apt-get install python3-setuptools

#- script: pip3 install ansible==2.9.2
    
- script: ansible-playbook create_env.yml
