- hosts: localhost

  tasks:
 
  - name: pwd value
    command: pwd
    register: result
    
  - debug:
      var: result
    
  - name: Get repository
    git:
      repo: 'https://github.com/toharikr/project.git'
      dest: $(Build.SourcesDirectory)

  - include_vars: $(Build.SourcesDirectory)/env.yml
  - debug: msg="Hello, {{ name }}!"
 
  - name: ansible create directory example
    file:
      path: ~/.azure
      state: directory
  - copy:
      src: $(Build.SourcesDirectory)/credentials
      dest: ~/.azure 
      
  - name: Create resource group
    azure_rm_resourcegroup:
        name: demorg
        location: eastus
    register: rg
  - debug:
        var: rg
        
  - name: Create resource group    
    openssh_keypair:
       path: /tmp/id_ssh_rsa
    register: res
  - debug: 
        var1: res 
  
  
  - name: Create a managed Azure Container Services (AKS) instance
    azure_rm_aks:
      name: myAKS
      location: eastus
      resource_group: demorg
      dns_prefix: akstest
      kubernetes_version: 1.14.6
    linux_profile:
      admin_username: azureuser
      ssh_key: ssh-rsa $(var1)
    service_principal:
      client_id: "694d098e-f2d8-4c03-8908-4ec256b8de86"
      client_secret: "VQ.7cqi6qpS32gY0kEO1432-_.h_E._2x~"
    agent_pool_profiles:
      - name: default
        count: 1
        vm_size: Standard_D2_v2
    tags:
      Environment: projectdev
