- hosts: localhost

  tasks:
 
  - name: pwd value
    command: pwd
    register: result
    
  - debug:
      var: result
    
  - name: Get repository
    git:
      repo: 'https://github.com/toharikr/project.git'
      dest: $(Build.SourcesDirectory)

  - include_vars: $(Build.SourcesDirectory)/env.yml
  - debug: msg="Hello, {{ name }}!"
  
  - script: mkdir ~/.azure
  - copy:
      src: $(Build.SourcesDirectory)/credentials
      dest: ~/.azure 
      
  - name: Create resource group
    azure_rm_resourcegroup:
        name: demorg
        location: eastus
    register: rg
  - debug:
        var: rg
      
