- hosts: localhost
  gather_facts: True
  vars:
      ansible_python_interpreter: /usr/bin/python3 
  
  tasks:
  
  - name: python verion
    command: whereis python
    register: result1
    
  - debug:
      var: result1
  
  - name: python verion
    command: python --version
    register: result2
  
  - debug:
      var: result2
      
  - name: ansible python version
    command: ~/.local/bin/ansible --version | grep "python version"
    register: result3
    
  - debug:
      var: result3 
 
 
  - name: Print message if ansible version is greater than 2.7.0
    debug:
      msg: "Ansible version is  {{ ansible_version.full }}"
      
  - name: pwd value
    command: pwd
    register: result
    
  - debug:
      var: result
      
  - name: Get repository
    git:
      repo: 'https://github.com/toharikr/project.git'
      dest: $(Build.SourcesDirectory)

  - include_vars: $(Build.SourcesDirectory)/env.yml
  - debug: msg="rg name {{ resourcegroup }} and aksname {{ aksname }} "
  
 
  - name: ansible create directory example
    file:
      path: ~/.azure
      state: directory
  - copy:
      src: $(Build.SourcesDirectory)/credentials
      dest: ~/.azure 
       
  - name: Create resource group
    azure_rm_resourcegroup:
        name: {{ resourcegroup }}
        location: eastus
        
  - name: Create resource group    
    openssh_keypair:
       path: /tmp/id_ssh_rsa
    register: res
  - name: show the value of output
    debug: var=res
 
  - name: Fix azure_rm_aks Bug
    get_url:
       url: https://raw.githubusercontent.com/haiyuazhang/ansible/features/lib/ansible/modules/cloud/azure/azure_rm_aks.py
       dest: ~/.local/lib/python3.6/site-packages/ansible/modules/cloud/azure/azure_rm_aks.py
       checksum: sha256:96a111b66aec128fc8165beb803ac8684a8b2d3e84ba7be6ae0db94a81457fd6
       
 
       
  - name: Create a managed Azure Container Services (AKS) instance
    azure_rm_aks:
      name: "{{ aksname }}"
      location: eastus2
      resource_group: "{{ resourcegroup }}"
      dns_prefix: "{{ aksname }}"
      kubernetes_version: 1.14.7
      linux_profile:
        admin_username: azureuser
        ssh_key: "{{ res.public_key }}"
      service_principal:
        client_id: "694d098e-f2d8-4c03-8908-4ec256b8de86"
        client_secret: "VQ.7cqi6qpS32gY0kEO1432-_.h_E._2x~"
      agent_pool_profiles:
        - name: default
          count: 1
          vm_size: Standard_D2_v2
      tags:
        Environment: projectdev
    register: aks  
    
  #- debug: msg="{{ aks.stdout }}"
