- hosts: localhost

  tasks:
 
  - name: pwd value
    command: pwd
    register: result
    
  - debug:
      var:: result
    
  - name: Get repository
    git:
      repo: 'https://github.com/toharikr/project.git'
      dest: /home/checkout
      version: dev
  - include_vars: env.yml
  - debug: msg="Hello, {{ name }}!"
      
