apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: toharikrproject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: toharikrproject 
    spec:
      containers:
        - name: toharikrproject 
          image: acrauto.azurecr.io/toharikrproject
          ports:
          - containerPort: 8080
