apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: toharikrdemoazure 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: toharikrdemoazure 
    spec:
      containers:
        - name: toharikrdemoazure 
          image: demoazurecr.azurecr.io/toharikrdemoazure
          ports:
          - containerPort: 8080
